BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "TAWASSOL"."ARRET_EMPLISSAGE"';
EXCEPTION
WHEN OTHERS THEN
  NULL;
END;
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "TAWASSOL"."CREUX_EMPLISSAGE"';
EXCEPTION
WHEN OTHERS THEN
  NULL;
END;
ALTER TABLE "TAWASSOL"."FICHE_MARCHE" MODIFY ("CADENCE_ARRETS_COMPRIS" FLOAT(126));
Insert into CAUSE_ARRET_EMPLISSAGE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,null,null,null,null,'pane1 ');
Insert into CAUSE_ARRET_EMPLISSAGE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,null,null,null,null,'pane2');