

DELETE FROM tawassol.COLUMNDEF where VIEW_NAME like 'PIECE_REGLEMENT';


INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'PIECE_REGLEMENT', null);


INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'dateReglement', 'date', null, '1', null, '0', '1', 'DATE', 'PIECE_REGLEMENT', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'dateEligible', 'date éligble', null, '2', null, '0', '1', 'DATE', 'PIECE_REGLEMENT', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'typePieceReglementLibelle', 'type de pièce', null, '3', null, '0', '1', 'TEXT', 'PIECE_REGLEMENT', 15,'typePieceReglement.libelle','PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'reference', 'référence', null, '4', null, '0', '1', 'TEXT', 'PIECE_REGLEMENT', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'montant', 'montant du', null, '4', null, '0', '1', 'NUMBER', 'PIECE_REGLEMENT', 10,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'montantRestant', 'montant restant', null, '4', null, '0', '1', 'NUMBER', 'PIECE_REGLEMENT', 10,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'soldee', 'soldée', null, '4', null, '0', '1', 'CHECKBOX', 'PIECE_REGLEMENT', 10,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'statut', 'statut', null, '4', null, '0', '1', 'ENUM', 'PIECE_REGLEMENT', 10,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'concessionnaireLibelle', 'concessionnaire', '1', '4', null, '0', '1', 'TEXT', 'PIECE_REGLEMENT', null,'concessionnaire.libelle','PERCENTAGE');