
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'DELEGATION', null);


INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'objet', 'Objet de dérogation', null, '1', null, '0', '1', 'ENUM', 'DELEGATION', 40,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'userUsername', 'délegué à', null, '2', null, '0', '1', 'TEXT', 'DELEGATION', 20,'user.username','PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'du', 'Du', null, '3', null, '0', '1', 'DATE', 'DELEGATION', 20,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'au', 'Au', null, '4', null, '0', '1', 'DATE', 'DELEGATION', 20,null,'PERCENTAGE');