
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'USERS', null);


INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'siteLibelle', 'Site', null, '1', null, '0', '1', 'TEXT', 'USERS', 25,'site.libelle','PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'firstname', 'Nom', null, '2', null, '0', '1', 'TEXT', 'USERS', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'lastname', 'Prénom', null, '3', null, '0', '1', 'TEXT', 'USERS', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'username', 'Login', null, '4', null, '0', '1', 'TEXT', 'USERS', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'profilType', 'Type', null, '4', null, '0', '1', 'ENUM', 'USERS', 15,null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'profilLibelle', 'Profil', null, '4', null, '0', '1', 'TEXT', 'USERS', 15,'profil.libelle','PERCENTAGE');