INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'FICHE_MARCHE', null,'PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'dateJournee', 'Date Journée', null, '2', null, '0', '1', 'DATE', 'FICHE_MARCHE', '12',null,'PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'postHeureDebut', 'Heure début', null, '3', null, '0', '1', 'TIME', 'FICHE_MARCHE', '11','post.heureDebut','PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'postHeureFin', 'Heure fin', null, '4', null, '0', '1', 'TIME', 'FICHE_MARCHE', '11','post.heureFin','PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'postLibelle', 'post', null, '5', null, '0', '1', 'TEXT', 'FICHE_MARCHE', '11','post.libelle','PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'userUsername', 'O.chaine', null, '6', null, '0', '1', 'TEXT', 'FICHE_MARCHE', '11','user.username','PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'produitLibelle', 'Type BD', null, '7', null, '0', '1', 'TEXT', 'FICHE_MARCHE', '11','produit.libelle','PERCENTAGE');        

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'qteEmplissageTotal', 'Qté Total', null, '8', null, '0', '1', 'NUMBER', 'FICHE_MARCHE', '11',null,'PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'cadenceArretsCompris', 'Cadence', null, '9', null, '0', '1', 'NUMBER', 'FICHE_MARCHE', '11',null,'PERCENTAGE');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'statut', 'Etat', null, '10', null, '0', '1', 'ENUM', 'FICHE_MARCHE', '11',null,'PERCENTAGE'); 