alter table "TAWASSOL"."EMPLISSAGE_CONTROLE_COLONNE" drop column "CONTROL_LIGNE_ID";
alter table "TAWASSOL"."EMPLISSAGE_CONTROLE_LIGNE" drop column "CONTROL_RESULT_ID";
ALTER TABLE "TAWASSOL"."EMPLISSAGE_RESULT_CONTROL" MODIFY ("EMPLISSAGE_ID" NOT NULL ENABLE);
ALTER TABLE "TAWASSOL"."EMPLISSAGE_RESULT_CONTROL" MODIFY ("RESULTAT" NULL);


Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD E','BD étrangère vide au client');
Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD SC','BD reçue sans chapeau');
Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD DA','BD à déformation anormale');
Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD V','BD à vidanger');

Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD PD','BD à pied déformé');
Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD SNP:','BD sale nécessitant Lavage et peinture');
Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD RD','BD avec robinet défectueux');
Insert into EMPLISSAGE_CONTROLE_COLONNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,ABREVIATION,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'1','','BD CR','BD nécessitant inspection (contrôle réglementaire)');

Insert into EMPLISSAGE_CONTROLE_LIGNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,null,null,null,null,'1',null,'Tri BD avant emplissage');
Insert into EMPLISSAGE_CONTROLE_LIGNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,null,null,null,null,'1',null,'Emplissage carousel');
Insert into EMPLISSAGE_CONTROLE_LIGNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,null,null,null,null,'1',null,'Contrôle d étanchéité par immersion dans l eau');
Insert into EMPLISSAGE_CONTROLE_LIGNE (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,ACTIVE,CODE,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,null,null,null,null,'1',null,'Contrôle d étanchéité DFE');


Insert into POST (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,HEURE_DEBUT,HEURE_FIN,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('06/07/17 08:00:00,822000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('06/07/17 12:00:00,050000000','DD/MM/RR HH24:MI:SSXFF'),'Post1');
Insert into POST (ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,HEURE_DEBUT,HEURE_FIN,LIBELLE) values (TAWASSOL.REF_DATA_SEQ.nextval,'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),'',to_timestamp('','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('06/07/17 14:00:00,822000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('06/07/17 18:00:00,050000000','DD/MM/RR HH24:MI:SSXFF'),'Post3');

