INSERT INTO "DESTINATION" ("ID", "ACTIVE", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval,'1', 'Rabat');
INSERT INTO "DESTINATION" ("ID", "ACTIVE", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval,'1',  'Agadir');
INSERT INTO "DESTINATION" ("ID", "ACTIVE", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval,'1',  'Marrakech');
INSERT INTO "DESTINATION" ("ID", "ACTIVE", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval,'1',  'Oujda');