DELETE FROM COLUMNDEF WHERE VIEW_NAME='EMPLISSAGE';

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'EMPLISSAGE', null,'PERCENTAGE');
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'numOE', 'N° OE', null, '2', null, '0', '1', 'TEXT', 'EMPLISSAGE', '20', null,'PERCENTAGE');
       INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'clientLibelle', 'Client', null, '3', null, '0', '1', 'TEXT', 'EMPLISSAGE', '15','client.libelle','PERCENTAGE');
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'concessionnaireLibelle', 'Concessionnaire', null, '4', null, '0', '1', 'TEXT', 'EMPLISSAGE', '15','concessionnaire.libelle','PERCENTAGE');        

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'statut', 'Statut', null, '5', null, '0', '1', 'ENUM', 'EMPLISSAGE', '15',null,'PERCENTAGE'); 
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'produitLibelle', 'Produit', null, '6', null, '0', '1', 'ENUM', 'EMPLISSAGE', '20','produit.libelle','PERCENTAGE'); 
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'qteEmplissage', 'Quantité', null, '7', null, '0', '1', 'ENUM', 'EMPLISSAGE', '15',null,'PERCENTAGE'); 

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,UNIT)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'origine', 'Origine', '1', '8', null, '0', '1', 'ENUM', 'EMPLISSAGE', null,'PERCENTAGE');
       
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD,UNIT) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'createdOn', 'Date de création', '1', '9', null, '0', '1', 'DATE', 'EMPLISSAGE', null,null,'PERCENTAGE'); 