INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'BON_LIVRAISON', null);
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'ordreLivraisonNumBC', 'N° BC / BCRG', null, '2', null, '0', '1', 'TEXT', 'BON_LIVRAISON', null,'ordreLivraison.numBC');
       INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'ordreLivraisonDateCommande', 'Date Commande', null, '3', null, '0', '1', 'DATE', 'BON_LIVRAISON', null,'ordreLivraison.dateCommande'); 
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'ordreLivraisonClientLibelle', 'Client', null, '4', null, '0', '1', 'TEXT', 'BON_LIVRAISON', null,'ordreLivraison.client.libelle');
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'ordreLivraisonConcessionnaireLibelle', 'Concessionnaire', null, '5', null, '0', '1', 'TEXT', 'BON_LIVRAISON', null,'ordreLivraison.concessionnaire.libelle');        
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'ordreLivraisonChauffeurNom', 'Chauffeur', null, '6', null, '0', '1', 'TEXT', 'BON_LIVRAISON', null,'ordreLivraison.chauffeur.nom');

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'statut', 'Etat', null, '7', null, '0', '1', 'ENUM', 'BON_LIVRAISON', null,null); 

INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD)
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'ordreLivraisonTypeBon', 'Type de Bon', '1', '8', null, '0', '1', 'ENUM', 'BON_LIVRAISON', null,'ordreLivraison.typeBon');
