#server:
#  contextPath: /tawassol/api
spring:
  main:
    banner-mode: 'OFF'
  profiles: prod
  datasource:
    hikari:
      maximumPool-size: 10
      idleTimeout: 30000
    #driverClassName: oracle.jdbc.pool.OracleDataSource
    #jdbcUrl: jdbc:oracle:thin:@localhost:1521:xe
    #jdbcUrl: jdbc:oracle:thin:@172.20.2.212:1521:xe
    #java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input=tawassol password=ayowork
    username: tifawin
    password: tifwork
    jdbcUrl: jdbc:mysql://127.0.0.1:3316/tawassol
    driverClassName: com.mysql.jdbc.Driver
    #type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: MYSQL
    hibernate:
      # Supported values include create, create-drop, update, and validate.
      ddl-auto: update
      naming:
        implicit-strategy: com.ayouris.tawassol.common.model.helper.cfg.CustomNamingStrategy
  flyway:
    enabled: false

  mail:
    default-encoding: UTF-8
    host: 127.0.0.1
    #jndi-name:
    username:
    password:
    port: 1025
    properties.*:
    protocol: smtp
    test-connection: false

  logging: # logging directory path configuration
    application.directory: /appli/tawassol/logs
    mail.directory: /appli/tawassol/logs/mail

logging:
  config: classpath:logback.xml