INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'PRODUIT', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'code', 'Code', null, '2', null, '0', '1', 'TEXT', 'PRODUIT', null,null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'libelle', 'Libellé', null, '3', null, '0', '1', 'TEXT', 'PRODUIT', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
		VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'poids', 'Poids (TM)', null, '4', null, '0', '1', 'NUMBER', 'PRODUIT', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'natureProduit', 'Nature', null, '5', null, '0', '1', 'ENUM', 'PRODUIT', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'unite', 'Unité', null, '6', null, '0', '1', 'TEXT', 'PRODUIT', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'typeChargement', 'Type Chargement', null, '7', null, '0', '1', 'ENUM', 'PRODUIT', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'active', 'Active', '1', '8', null, '0', '1', 'CHECKBOX', 'PRODUIT', null);
