INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'CONTROLE_CAMION', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'controle', 'Contôle', null, '2', null, '0', '1', 'TEXT', 'CONTROLE_CAMION', null,null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'typeChargement', 'Type Chargement', null, '3', null, '0', '1', 'ENUM', 'CONTROLE_CAMION', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'active', 'Active', '1', '4', null, '0', '1', 'CHECKBOX', 'CONTROLE_CAMION', null);
