INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'CAMION', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'matricule', 'N° camion', null, '2', null, '0', '1', 'TEXT', 'CAMION', null,null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'concessionnaireLibelle', 'concessionnaire', null, '3', null, '0', '1', 'TEXT', 'CAMION', null,'concessionnaire.libelle');
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'typeCamion', 'Type camion', null, '4', null, '0', '1', 'ENUM', 'CAMION', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD)
		VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'marqueLibelle', 'Marque', null, '5', null, '0', '1', 'TEXT', 'CAMION', null,'marque.libelle');
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'active', 'Active', '1', '6', null, '0', '1', 'CHECKBOX', 'CAMION', null);
