INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH,NESTED_FIELD) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'concessionnaireLibelle', 'Concessionnaire', null, '2', null, '0', '1', 'TEXT', 'CHAUFFEUR', null,'concessionnaire.libelle');
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH) 
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'cin', 'N° CIN', null, '3', null, '0', '1', 'TEXT', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
		VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'permis', 'N° Permis', null, '4', null, '0', '1', 'TEXT', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'nom', 'Nom', null, '5', null, '0', '1', 'TEXT', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'prenom', 'Prénom', null, '6', null, '0', '1', 'TEXT', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'tel', 'Tel', null, '7', null, '0', '1', 'TEXT', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'ville', 'Ville', null, '8', null, '0', '1', 'TEXT', 'CHAUFFEUR', null);
INSERT INTO "GWIC"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
       VALUES (GWIC.REF_DATA_SEQ.nextval, '0', 'active', 'Active', '1', '9', null, '0', '1', 'CHECKBOX', 'CHAUFFEUR', null);