INSERT INTO "MARQUE" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Nissan');
INSERT INTO "MARQUE" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Scania');
INSERT INTO "MARQUE" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Mitsubishi');
INSERT INTO "MARQUE" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Mercedes');