INSERT INTO "FABRIQUANT" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Fabriquant 1');
INSERT INTO "FABRIQUANT" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Fabriquant 2');
INSERT INTO "FABRIQUANT" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Fabriquant 3');
INSERT INTO "FABRIQUANT" ("ID", "LIBELLE") VALUES (TAWASSOL.REF_DATA_SEQ.nextval, 'Fabriquant 4');