
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH) 
       VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'id', 'ID', '1', '1', null, '0', '1', 'NUMBER', 'TYPE_FILE_ATTENTE', null);
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
		VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'type', 'Type', null, '2', null, '0', '1', 'TEXT', 'TYPE_FILE_ATTENTE', null);
INSERT INTO "TAWASSOL"."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH)
		VALUES (TAWASSOL.REF_DATA_SEQ.nextval, '0', 'categorie', 'Catégorie', null, '2', null, '0', '1', 'ENUM', 'TYPE_FILE_ATTENTE', null);
INSERT INTO "GTAWASSOL."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH) 
       VALUES (GTAWASSOLREF_DATA_SEQ.nextval, '0', 'typePardefaut', 'Type par defaut', null, '4', null, '0', '1', 'CHECKBOX', 'TYPE_FILE_ATTENTE', null);
INSERT INTO "GTAWASSOL."COLUMNDEF" (ID,EDITABLE,FIELD,HEADER_NAME,COLUMN_HIDE,COLUMN_ORDER,PINNED,SUPPRESS_SORTING,SUPRESS_MENU,COLUMN_TYPE,VIEW_NAME,WIDTH) 
       VALUES (GTAWASSOLREF_DATA_SEQ.nextval, '0', 'active', 'Active', '1', '5', null, '0', '1', 'CHECKBOX', 'TYPE_FILE_ATTENTE', null);
       
